# Generated by Django 3.0.5 on 2020-04-21 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_encounters_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounters',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
