# Generated by Django 3.0.5 on 2020-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Blinded', 'Blinded'), ('Charmed', 'Charmed'), ('Deafened', 'Deafened'), ('Fatigued', 'Fatigued'), ('Frightened', 'Frightened'), ('Grappled', 'Grappled'), ('Incapacitated', 'Incapacitated'), ('Invisible', 'Invisible'), ('Paralyzed', 'Paralyzed'), ('Petrified', 'Petrified'), ('Poisoned', 'Poisoned'), ('Prone', 'Prone'), ('Restrained', 'Restrained'), ('Stunned', 'Stunned')], max_length=13)),
            ],
        ),
    ]
