# Generated by Django 3.0.5 on 2020-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='conscious',
            field=models.BooleanField(default=True),
        ),
    ]
