# Generated by Django 3.0.5 on 2020-04-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0002_creature_conscious'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='secondary_status',
            field=models.CharField(blank=True, choices=[('Blinded', 'Blinded'), ('Charmed', 'Charmed'), ('Deafened', 'Deafened'), ('Fatigued', 'Fatigued'), ('Frightened', 'Frightened'), ('Grappled', 'Grappled'), ('Incapacitated', 'Incapacitated'), ('Invisible', 'Invisible'), ('Paralyzed', 'Paralyzed'), ('Petrified', 'Petrified'), ('Poisoned', 'Poisoned'), ('Prone', 'Prone'), ('Restrained', 'Restrained'), ('Stunned', 'Stunned')], max_length=13),
        ),
        migrations.AddField(
            model_name='creature',
            name='tertiary_status',
            field=models.CharField(blank=True, choices=[('Blinded', 'Blinded'), ('Charmed', 'Charmed'), ('Deafened', 'Deafened'), ('Fatigued', 'Fatigued'), ('Frightened', 'Frightened'), ('Grappled', 'Grappled'), ('Incapacitated', 'Incapacitated'), ('Invisible', 'Invisible'), ('Paralyzed', 'Paralyzed'), ('Petrified', 'Petrified'), ('Poisoned', 'Poisoned'), ('Prone', 'Prone'), ('Restrained', 'Restrained'), ('Stunned', 'Stunned')], max_length=13),
        ),
    ]
