# Generated by Django 3.0.5 on 2020-04-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0003_auto_20200415_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='original_hp',
            new_name='max_hp',
        ),
    ]
